[package]
name = "ajson"
version = "0.2.4"
authors = ["importcjj <importcjj@gmail.com>"]
license = "MIT"
description = "JSON Parser for Rust - Get JSON values quickly"
keywords = ["json", "json-parser", "gjson", "ajson"]
categories = ["encoding"]
readme = "README.md"
documentation = "https://docs.rs/ajson/latest/ajson/"
repository = "https://github.com/importcjj/rust-ajson"
include = ["Cargo.toml", "src/**/*.rs", "README.md", "LICENSE-MIT"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
autobenches = false

[features]
default = []
wild = ["regex"]

[dependencies]
regex = { version = "1", optional = true }

[dev-dependencies]
criterion = "0.2"
json = "0.11.13"
serde_json = "1.0"
serde = { version = "1.0.98", features = ["derive"] }
nom = "5"

[[bench]]
name = "ajson_benchmark"
path = "benches/ajson_benchmark.rs"
harness = false
